const useStyles = () => ({
  singleCardRecordDesktop: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    marginRight: '-20px',
    marginLeft: '-20px',
    padding: '15px',
    height: '100px',
    width: '100%',
    marginBottom: '30px',
  },
  singleCardRecordMobile: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    marginRight: '-20px',
    marginLeft: '-20px',
    padding: '15px',
    width: '100%',
    marginBottom: '30px',
  },
  singleCardRecordHeading: {
    color: '#9494A4',
    fontFamily: 'Manrope-Bold',
    fontSize: 'calc(0.4em + 1vmin)',
  },
  singleCardRecordBottomPartDesktop: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: '20px',
    justifyContent: 'space-between',
  },
  singleCardRecordBottomPartMobile: {
    display: 'flex',
      flexWrap: 'wrap',
    flexDirection: 'column',
    alignContent: 'center',
    alignItems: 'center',
    padding: '20px',
    justifyContent: 'space-between',
  },
  singleCardRecordBottomPartDesktopLeftPart: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '8px',
  },
  singleCardRecordBottomPartMobileLeftPart: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5px',
    marginBottom: '20px',
    marginLeft: '15px',
  },
  singleCardRecordBottomPartMobileLeftPart240: {
    display: 'flex',
    flexDirection: 'column',
    alignContent: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '5px',
    marginBottom: '2px',
    marginLeft: '15px',
  },
  userAvatar: {
    height: 'calc(1em + 0.8vmin)',
    weight: 'calc(1em + 0.8vmin)',
    borderRadius: '6px',
    marginRight: '10px',
  },
  userAvatar240 : {
    height: 'calc(1em + 0.8vmin)',
    weight: 'calc(1em + 0.8vmin)',
    borderRadius: '6px',
    marginRight: '10px',
    marginTop: '20px',
  },
  addPersonButton: {
    marginLeft: '-12px',
  },
  singleCardRecordBottomPartRightPart: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    margin:'6px',
  },
  singleCardRecordBottomPartRightPart240: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
    margin:'10px',
    padding: '10px',
  },
  percentageBox: {
    backgroundColor: '#7171BF',
    fontFamily: 'Manrope-Bold',
    fontSize: 'calc(0.4em + 0.9vmin)',
    padding: '5px',
    borderRadius: '6px',
    alignText: 'center',
    color: 'white',
  },
  percentageBox240: {
    backgroundColor: '#7171BF',
    fontFamily: 'Manrope-Bold',
    fontSize: 'calc(0.4em + 0.9vmin)',
    padding: '5px',
    borderRadius: '6px',
    alignText: 'center',
    color: 'white',
    marginTop: '20px',
  },
  dateIcon: {
    height: 'calc(0.3em + 0.8vmin)',
    weight: 'calc(0.3em + 0.8vmin)'
  },

  dateBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F5',
    fontFamily: 'Manrope-Bold',
    fontSize: 'calc(0.4em + 0.8vmin)',
    padding: '3px',
    borderRadius: '6px',
    marginLeft:'6px',
    width: 'calc(9em + 1vmin)',
    alignText: 'center',
    marginRight: '7px',
  }
});
export default useStyles;