const useStyles = () => ({
  singleCardRecordDesktop: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    marginRight: '-20px',
    marginLeft: '-20px',
    padding: '15px',
    height: '100px',
    width: '100%',
    overflowY: 'scroll',
    overflowX: 'scroll',
    marginBottom: '30px',
  },
  singleCardRecordMobile: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    marginRight: '-20px',
    marginLeft: '-20px',
    padding: '15px',
    height: '180px',
    width: '100%',
    overflowY: 'scroll',
    overflowX: 'scroll',
    marginBottom: '30px',
  },
  singleCardRecordHeading: {
    color: '#9494A4',
    fontFamily: 'Manrope-Bold',
    fontSize: '12px',
  },
  singleCardRecordBottomPartDesktop: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: '20px',
    justifyContent: 'space-between',
  },
  singleCardRecordBottomPartMobile: {
    display: 'flex',
    flexDirection: 'column',
    alignContent: 'center',
    alignItems: 'center',
    margin: '20px',
    justifyContent: 'space-between',
  },
  singleCardRecordBottomPartDesktopLeftPart: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5px',
  },
  singleCardRecordBottomPartMobileLeftPart: {
    display: 'flex',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5px',
    marginBottom: '20px',
    marginLeft: '15px',
  },
  userAvatar: {
    width: '26px',
    height: '26px',
    borderRadius: '6px',
    marginRight: '10px',
  },
  addPersonButton: {
    marginLeft: '0px',
  },
  singleCardRecordBottomPartRightPart: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginRight:'6px',
  },
  percentageBox: {
    backgroundColor: '#7171BF',
    fontFamily: 'Manrope-Regular',
    fontSize: '12px',
    padding: '5px',
    borderRadius: '6px',
    width: '25px',
    height: '20px',
    alignText: 'center',
    color: 'white',
  },
  dateBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F5',
    fontFamily: 'Manrope-Regular',
    fontSize: '11px',
    padding: '5px',
    borderRadius: '6px',
    width: '85px',
    height: '20px',
    alignText: 'center',
    marginRight: '10px',
  }
});
export default useStyles;